name: Update README

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install stable toolchain
        run: rustup toolchain install stable

      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Compile and run the Rust program
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: cargo run --release --locked

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "update readme with latest stats :3"
          file_pattern: "README.md"